# Generated by Django 6.0.4 on 2026-09-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=100, unique=True)),
                ('game_creator', models.CharField(max_length=100)),
                ('game_opponent', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(default='---------', max_length=9)),
                ('current_turn', models.CharField(default='', max_length=100)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('is_over', models.BooleanField(default=False)),
            ],
        ),
    ]
